FROM node:14

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8080
CMD [ "node", "server.js" ]

#docker build -f Dockerfile.server -t federicoquartieri/server .
#docker run -d -p 5000:5000 federicoquartieri/server
#docker push federicoquartieri/server